name: build-openfire
on: push

env:
  IMAGE_NAME: abra7134/openfire
  OPENFIRE_VERSION: v4.7.1
  REGISTRY: docker.io

jobs:
  build:
    name: Build Openfire
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: igniterealtime/Openfire
          ref: ${{ env.OPENFIRE_VERSION }}

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          architecture: x64
          cache: maven
          distribution: adopt
          java-version: '11'

      - name: Run build
        run: make build-openfire

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ./build/docker/entrypoint.sh
            ./distribution/target/distribution-base
            ./Dockerfile
          key: distribution-base-${{ env.OPENFIRE_VERSION }}

  build_and_push_docker_image:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Get the build from cache
        uses: actions/cache@v3
        with:
          path: |
            ./build/docker/entrypoint.sh
            ./distribution/target/distribution-base
            ./Dockerfile
          key: distribution-base-${{ env.OPENFIRE_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.OPENFIRE_VERSION }}
